# Generated by Django 5.2.8 on 2026-01-18 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='category_descriptions/', verbose_name='Зображення')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Завантажено')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Оригінальна назва')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='description_images', to='categories.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Зображення опису',
                'verbose_name_plural': 'Зображення описів',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
