# Generated by Django 5.2.8 on 2026-01-28 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Зображення категорії', 'verbose_name_plural': 'Зображення категорій'},
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='categories.category', verbose_name='Категорія'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(upload_to='category_images/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Оригінальна назва файлу'),
        ),
    ]
