# Generated by Django 5.2.8 on 2026-01-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_categoryimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
